### ISSUE TITLE
Clarification needed on definition of semihosting traps

### ISSUE THREAD

**Issue by Silabs-ArjanB** [riscv-non-isa/riscv-semihosting#10]
Section "2.3 Semihosting Execution Environment" refers to the RISC-V external debug specification as follows:

> Of particular interest is the RISC-V external debug specification, which allows M-mode (and optionally S/U modes) ebreak instructions to be treated as semihosting traps.

The RISC-V external debug specification however does not mention the word semihosting at all. Can some explanation be added here using _actual terminology_ from the RISC-V external debug specification about what it means to be '_treated as semihosting traps_'?

**Comment by avpatel** [comment]
The section 2.3 has stale text and should be remove. I will update and create a 0.4 release tag.
