### ISSUE TITLE
Missing `the`

### ISSUE THREAD

**Issue by xypron** [riscv-non-isa/riscv-semihosting#12]
https://github.com/riscv-non-isa/riscv-semihosting/blob/0a1e3af84f77dec0a69a0d6904a9cf59f134265b/src/intro.adoc?plain=1#L11

%s/design of publicly/design of the publicly/

**Comment by TommyMurphyTM1234** [comment]
Shouldn't it be "a" rather than "the" as there may be other comparable specifications out there too and the Arm one is just one example?

**Comment by avpatel** [comment]
Actually, the ARM one is the only semihosting specification available out there. In the future, if some other semihosting spec shows up then we can define a different trap/breakpoint instruction sequence for it.

**Comment by ilg-ul** [comment]
> we can define a different trap/breakpoint instruction sequence for it.

The immediate field in the second dummy shift instruction is wide enough to encode as many IDs as needed (I chose the value 7 for the first one - Arm semihosting - for no particular reason).

However, at least for the foreseeable future, I doubt there will be any.
