### ISSUE TITLE
Avoid table split by page break.

### ISSUE THREAD

**Issue by xypron** [riscv-non-isa/riscv-semihosting#13]
https://github.com/riscv-non-isa/riscv-semihosting/blob/0a1e3af84f77dec0a69a0d6904a9cf59f134265b/src/binary-interface.adoc?plain=1#L55

Currently Table 1. "RISC-V Registers and field size" is split by a page break in the pdf.

**Comment by ilg-ul** [comment]
The break inserted in https://github.com/riscv-non-isa/riscv-semihosting/commit/9535facddcceae3ffcc3ecbbf633907882286378 does not seem effective, the Table 1 is still split in the 0.5 release.

**Comment by avpatel** [comment]
Hmm, strange. I don't see the table split in 0.5 release [PDF](https://github.com/riscv-non-isa/riscv-semihosting/releases/download/0.5/riscv-semihosting.pdf).

**Comment by ilg-ul** [comment]
Strange indeed, now I see it ok on my Mac too. It might have been a glitch (on my tablet or in my mind) :-(

Sorry for the noise.
