### ISSUE TITLE
Confusing/unclear text

### ISSUE THREAD

**Issue by TommyMurphyTM1234** [riscv-non-isa/riscv-semihosting#15]
This sentence is grammatically incorrect and it's unclear what exactly it is trying to say so I cannot offer an alternative wording unfortunately:

> Only the mechanism of invoke a semihosting service (aka semihosting binary interface) is architecture specific whereas all defined semihosting services [1] are architecture independent and resemble system calls of an unix-style operating system. 

"Of invoking" instead of "of invoke"?
"Unix" instead of "unix"?
But I think that the whole sentence needs a review to be clearer.

**Comment by ilg-ul** [comment]
The sentence is confusing indeed, but the meaning is probably that the semihosting services themselves as defined by Arm are portable across different architectures, and only the sequence of assembly instructions used to encode a dedicated break instruction is specific to each architecture.

**Comment by avpatel** [comment]
> The sentence is confusing indeed, but the meaning is probably that the semihosting services themselves as defined by Arm are portable across different architectures, and only the sequence of assembly instructions used to encode a dedicated break instruction is specific to each architecture.

I will reword the text based on this suggestion.
