### ISSUE TITLE
Semihosting binary interface description

### ISSUE THREAD

**Issue by TommyMurphyTM1234** [riscv-non-isa/riscv-semihosting#16]
> The RISC-V semihosting binary interface consist of a trap instruction sequence

Surely it's a **breakpoint** instruction sequence?

**Comment by ilg-ul** [comment]
According to Arm, this is a an instruction that must be always understood as a breakpoint, and the execution must halt at his point.

If the debugger supports semihosting, and semihosting is enabled, the debugger must check whether the breakpoint is a regular one or a semihosting breakpoint. In the second case it must process the requested service and resume execution.

So yes, semihosting services are invoked via custom software breakpoints.

**Comment by avpatel** [comment]
I will update the text to use "breakpoint instruction sequence" instead of "trap instruction sequence"
