### ISSUE TITLE
Listing 1 is confusing

### ISSUE THREAD

**Issue by ilg-ul** [riscv-non-isa/riscv-semihosting#21]
The comment in the third line is too long, and `number 7` is rendered on the next line, which is confusing.

I suggest to shorten the comment to fit the line.

**Comment by avpatel** [comment]
This was already reported https://github.com/riscv-non-isa/riscv-semihosting/issues/11 and has been fixed by https://github.com/riscv-non-isa/riscv-semihosting/commit/5d4dfc21642d77ad8275a04af1b2914212c66a22
