### ISSUE TITLE
Clarify paging requirement

### ISSUE THREAD

**Issue by xypron** [riscv-non-isa/riscv-semihosting#22]
"If address translation and protection is enabled for the semihosting caller then the
semihosting instruction sequence and data passed via memory must be paged in else the behavior of
the semihosting call is UNSPECIFIED."

I understand that if paging is active the pages containing the three instructions and the data must be paged in. But what protection does the sentence refer to?

Can we replace the term "address translation and protection" by "memory paging"?

**Comment by avpatel** [comment]
The term "address translation and protection" is used for "memory paging" in RISC-V specs hence we use the same term in semihosting spec as well.
